"""A worked example of a GaleQEA reporter plugin.

Demonstrates the three things every plugin should do:

1. Declare only the capabilities it needs, and check them at setup rather than
   discovering the failure halfway through a run.
2. Fail without taking anything else down - a reporter that raises must not fail
   the run it is reporting on.
3. Produce output a human actually wants to read: new failures first, because
   that is the only part of a red run that is news.
"""

from __future__ import annotations

from datetime import datetime
from pathlib import Path

from galeqea.plugins.sdk import PluginContext, Reporter


class MarkdownReporter(Reporter):
    def setup(self, ctx: PluginContext) -> None:
        ctx.require("read:runs")
        self.output_dir = Path.home() / ".galeqea" / "reports"
        self.output_dir.mkdir(parents=True, exist_ok=True)
        ctx.log(f"markdown-reporter writing to {self.output_dir}")

    def on_run_finished(self, run: dict, results: list[dict], ctx: PluginContext) -> None:
        try:
            path = self.output_dir / f"run-{run.get('number', 'x')}.md"
            path.write_text(self._render(run, results))
            ctx.log(f"wrote {path}")
        except Exception as exc:  # noqa: BLE001
            # A reporter must never fail the run it reports on.
            ctx.log(f"report failed (run unaffected): {exc}")

    # ------------------------------------------------------------------ #
    def _render(self, run: dict, results: list[dict]) -> str:
        triage = run.get("triage") or {}
        totals = run.get("totals") or {}

        lines = [
            f"# Run #{run.get('number')} — {run.get('status')}",
            "",
            f"*{datetime.now():%Y-%m-%d %H:%M}* · environment `{run.get('environment')}` "
            f"· {run.get('duration_ms', 0) / 1000:.1f}s",
            "",
            f"> {triage.get('headline', 'No triage summary available.')}",
            "",
            "| passed | failed | needs review | total |",
            "|---:|---:|---:|---:|",
            f"| {totals.get('passed', 0)} | {totals.get('failed', 0)} "
            f"| {totals.get('needs_review', 0)} | {totals.get('total', 0)} |",
            "",
        ]

        # New failures first: known and flaky failures are noise for triage.
        for bucket, heading in [
            ("new", "New failures — start here"),
            ("test_defect", "Test-side defects"),
            ("known", "Known failures"),
            ("flaky", "Flaky"),
            ("environment", "Environmental"),
        ]:
            entries = triage.get(bucket) or []
            if not entries:
                continue
            lines += [f"## {heading} ({len(entries)})", ""]
            for entry in entries:
                lines.append(f"- **{entry.get('key')}** — {entry.get('title', '')}")
                if entry.get("reason"):
                    lines.append(f"  - _{entry['reason']}_")
                if entry.get("error"):
                    lines.append(f"  - `{entry['error'][:160]}`")
            lines.append("")

        if not any(triage.get(b) for b in ("new", "test_defect", "known", "flaky", "environment")):
            lines += ["Nothing failed.", ""]

        lines += ["---", "", f"_Generated by markdown-reporter for run `{run.get('id')}`._"]
        return "\n".join(lines)


plugin = MarkdownReporter
