"""The typed test plan: all test types, deterministic, versioned by toggles."""

from __future__ import annotations

import uuid

from galeqea.ai.orchestrator import Orchestrator
from galeqea.models import ChatSession, Role, User
from galeqea.services import test_plan as tp

_DISC = {"base": "https://x.com",
         "pages": ["https://x.com", "https://x.com/a", "https://x.com/b"],
         "forms": 2, "discovered": 3, "apis": []}


def test_plan_covers_every_test_type():
    plan = tp.build_typed_plan(_DISC)
    keys = {r["key"] for r in plan["types"]}
    for expected in ("functional", "forms", "links", "a11y", "perf", "visual",
                     "responsive", "cross_browser", "security", "seo", "resilience",
                     "data_driven", "exploratory", "manual"):
        assert expected in keys, expected


def test_each_row_carries_risk_confidence_and_estimates():
    plan = tp.build_typed_plan(_DISC)
    for r in plan["types"]:
        assert r["risk"] in {"critical", "high", "medium", "low"}
        assert r["confidence"] in {"High", "Med", "Low"}
        assert r["est_minutes"] >= 0 and r["rerun_tokens"] == 0


def test_deterministic_types_cost_zero_build_tokens():
    plan = tp.build_typed_plan(_DISC)
    by_key = {r["key"]: r for r in plan["types"]}
    # These are generated by rule, so no model authoring cost.
    for key in ("functional", "a11y", "perf", "security", "seo"):
        assert by_key[key]["est_tokens"] == 0, key
    # Forms need authored variants → non-zero when enabled.
    assert by_key["forms"]["est_tokens"] > 0


def test_form_types_vanish_when_there_are_no_forms():
    plan = tp.build_typed_plan({**_DISC, "forms": 0})
    keys = {r["key"] for r in plan["types"]}
    assert "forms" not in keys and "data_driven" not in keys


def test_toggle_produces_a_new_version_and_diff():
    v1 = tp.build_typed_plan(_DISC)
    assert not any(r["key"] == "visual" and r["enabled"] for r in v1["types"])
    v2 = tp.toggle(v1, "visual", True)
    assert v2["version"] == v1["version"] + 1
    assert any(r["key"] == "visual" and r["enabled"] for r in v2["types"])
    assert v2["totals"]["types_enabled"] == v1["totals"]["types_enabled"] + 1
    assert "enabled Visual" in " ".join(tp.diff(v1, v2))


def test_discovery_shape_is_tolerant():
    # forms/apis/pages as ints (not lists) must not crash, and a minimal dict works.
    plan = tp.build_typed_plan({"base": "https://x.com", "pages": 2, "forms": 1, "apis": 1})
    assert plan["totals"]["types_total"] > 0
    assert any(r["key"] == "api" and r["count"] == 1 for r in plan["types"])
    assert any(r["key"] == "forms" for r in plan["types"])
    tp.build_typed_plan({"base": "https://x.com"})  # only base, no crash


def test_markdown_is_versioned_and_tabular():
    md = tp.plan_markdown(tp.build_typed_plan(_DISC))
    assert md.startswith("# Test plan v1") and "| Type |" in md


async def test_plan_card_carries_test_types_and_toggle_versions(db, project, monkeypatch):
    from galeqea.services import website_test as wt

    def fake_discover(url, limit=8, timeout=90.0):
        base = url.rstrip("/")
        return {"ok": True, "base": base, "pages": [base, base + "/a"], "forms": 1,
                "status": 200, "method": "browser", "findings": [],
                "skipped": {"auth": 0, "error": 0, "offsite": 0}, "truncated": False, "discovered": 2}

    monkeypatch.setattr(wt, "discover_pages", fake_discover)
    user = User(email=f"u-{uuid.uuid4().hex[:8]}@x.io", name="U", role=Role.OWNER.value)
    session = ChatSession(project_id=project.id, title="t")
    db.add_all([user, session])
    db.commit()
    orch = Orchestrator(db, provider=None, project_id=project.id)

    await orch.handle(session=session, user=user, text="test https://example.com")  # guardrails
    plan_reply = await orch.handle(session=session, user=user, text="continue")      # plan
    block = plan_reply.blocks[0]
    assert block["type"] == "website_plan"
    assert block["test_types"] and block["plan_version"] == 1
    assert any(r["key"] == "a11y" for r in block["test_types"])

    toggled = await orch.handle(session=session, user=user, text="enable visual snapshots")
    assert toggled.blocks[0]["plan_version"] == 2
    assert any(r["key"] == "visual" and r["enabled"] for r in toggled.blocks[0]["test_types"])
