"""report page for confluence

Revision ID: 320df4b6711b
Revises: b9a6869aaad3
Create Date: 2026-08-29 13:19:06.640112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import galeqea.models.base


# revision identifiers, used by Alembic.
revision: str = '320df4b6711b'
down_revision: Union[str, Sequence[str], None] = 'b9a6869aaad3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_pages',
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('milestone_id', sa.String(length=40), nullable=False),
    sa.Column('space_key', sa.String(length=64), nullable=False),
    sa.Column('page_id', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('url', sa.String(length=600), nullable=False),
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'milestone_id', 'space_key', name='uq_report_page')
    )
    with op.batch_alter_table('report_pages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_pages_milestone_id'), ['milestone_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_pages_project_id'), ['project_id'], unique=False)

    # NOTE: alembic's milestone partial-index drop is a false positive — removed.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    with op.batch_alter_table('report_pages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_pages_project_id'))
        batch_op.drop_index(batch_op.f('ix_report_pages_milestone_id'))

    op.drop_table('report_pages')
    # ### end Alembic commands ###
