"""step cache table

Revision ID: 3c3acf14532a
Revises: 320df4b6711b
Create Date: 2026-08-29 14:40:46.684452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import galeqea.models.base


# revision identifiers, used by Alembic.
revision: str = '3c3acf14532a'
down_revision: Union[str, Sequence[str], None] = '320df4b6711b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('step_cache',
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('cache_key', sa.String(length=64), nullable=False),
    sa.Column('intent', sa.Text(), nullable=False),
    sa.Column('page_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('ladder', galeqea.models.base.JSONish(), nullable=False),
    sa.Column('params', galeqea.models.base.JSONish(), nullable=False),
    sa.Column('provenance', galeqea.models.base.JSONish(), nullable=False),
    sa.Column('hits', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'cache_key', name='uq_step_cache')
    )
    with op.batch_alter_table('step_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_step_cache_cache_key'), ['cache_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_step_cache_project_id'), ['project_id'], unique=False)

    # NOTE: alembic's milestone partial-index drop is a false positive — removed.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('step_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_step_cache_project_id'))
        batch_op.drop_index(batch_op.f('ix_step_cache_cache_key'))

    op.drop_table('step_cache')
    # ### end Alembic commands ###
