"""jira issue map for story import

Revision ID: 3c8d0605c00f
Revises: da97ca2015c5
Create Date: 2026-08-29 12:58:39.989895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import galeqea.models.base


# revision identifiers, used by Alembic.
revision: str = '3c8d0605c00f'
down_revision: Union[str, Sequence[str], None] = 'da97ca2015c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jira_issue_maps',
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('issue_id', sa.String(length=64), nullable=False),
    sa.Column('issue_key', sa.String(length=64), nullable=False),
    sa.Column('requirement_ref', sa.String(length=64), nullable=False),
    sa.Column('description_hash', sa.String(length=64), nullable=False),
    sa.Column('remote_updated', sa.String(length=40), nullable=False),
    sa.Column('stale', sa.Boolean(), nullable=False),
    sa.Column('coverage_written', sa.Boolean(), nullable=False),
    sa.Column('last_checked_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'issue_id', name='uq_jira_issue_map')
    )
    with op.batch_alter_table('jira_issue_maps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jira_issue_maps_issue_id'), ['issue_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jira_issue_maps_issue_key'), ['issue_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_jira_issue_maps_project_id'), ['project_id'], unique=False)
    # NOTE: alembic's proposed drop of the milestones `uq_milestone_project_version`
    # partial index is a false positive (autogen can't round-trip a WHERE index) —
    # removed by hand so this migration keeps the WO#5 guard intact.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    with op.batch_alter_table('jira_issue_maps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jira_issue_maps_project_id'))
        batch_op.drop_index(batch_op.f('ix_jira_issue_maps_issue_key'))
        batch_op.drop_index(batch_op.f('ix_jira_issue_maps_issue_id'))

    op.drop_table('jira_issue_maps')
    # ### end Alembic commands ###
