"""baseline schema

Revision ID: 42c3921c27bf
Revises: 
Create Date: 2026-08-29 06:25:10.580856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import galeqea.models.base


# revision identifiers, used by Alembic.
revision: str = '42c3921c27bf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_traces',
    sa.Column('project_id', sa.String(length=40), nullable=True),
    sa.Column('session_id', sa.String(length=40), nullable=True),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('agent_role', sa.String(length=48), nullable=False),
    sa.Column('provider', sa.String(length=48), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('steps', galeqea.models.base.JSONish(), nullable=False),
    sa.Column('prompt_sha256', sa.String(length=64), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('finished_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_traces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_traces_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_traces_session_id'), ['session_id'], unique=False)

    op.create_table('anomaly_records',
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('run_id', sa.String(length=40), nullable=True),
    sa.Column('scope', sa.String(length=32), nullable=False),
    sa.Column('metric', sa.String(length=64), nullable=False),
    sa.Column('subject_id', sa.String(length=40), nullable=True),
    sa.Column('observed', sa.Float(), nullable=False),
    sa.Column('expected', sa.Float(), nullable=False),
    sa.Column('deviation_sigma', sa.Float(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('detail', galeqea.models.base.JSONish(), nullable=False),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('anomaly_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_anomaly_records_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_anomaly_records_run_id'), ['run_id'], unique=False)

    op.create_table('approval_batches',
    sa.Column('project_id', sa.String(length=40), nullable=True),
    sa.Column('title', sa.String(length=400), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.Column('decided_by', sa.String(length=40), nullable=True),
    sa.Column('decided_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approval_batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approval_batches_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_batches_status'), ['status'], unique=False)

    op.create_table('approval_requests',
    sa.Column('project_id', sa.String(length=40), nullable=True),
    sa.Column('batch_id', sa.String(length=40), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=48), nullable=False),
    sa.Column('resource_id', sa.String(length=40), nullable=True),
    sa.Column('title', sa.String(length=400), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('payload', galeqea.models.base.JSONish(), nullable=False),
    sa.Column('diff', galeqea.models.base.JSONish(), nullable=False),
    sa.Column('evidence', galeqea.models.base.JSONish(), nullable=False),
    sa.Column('risk', sa.String(length=16), nullable=False),
    sa.Column('required_role', sa.String(length=20), nullable=False),
    sa.Column('requested_by', sa.String(length=40), nullable=True),
    sa.Column('requested_by_kind', sa.String(length=16), nullable=False),
    sa.Column('agent_role', sa.String(length=48), nullable=False),
    sa.Column('trace_id', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('decided_by', sa.String(length=40), nullable=True),
    sa.Column('decided_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('decision_comment', sa.Text(), nullable=False),
    sa.Column('expires_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('applied_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('apply_error', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approval_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approval_requests_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_requests_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_requests_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_requests_risk'), ['risk'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_requests_status'), ['status'], unique=False)

    op.create_table('artifacts',
    sa.Column('run_id', sa.String(length=40), nullable=True),
    sa.Column('run_test_id', sa.String(length=40), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('path', sa.String(length=1000), nullable=False),
    sa.Column('label', sa.String(length=300), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('meta', galeqea.models.base.JSONish(), nullable=False),
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artifacts_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_artifacts_run_test_id'), ['run_test_id'], unique=False)

    op.create_table('audit_events',
    sa.Column('seq', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=True),
    sa.Column('actor_id', sa.String(length=40), nullable=True),
    sa.Column('actor_kind', sa.String(length=16), nullable=False),
    sa.Column('actor_label', sa.String(length=200), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('resource_type', sa.String(length=48), nullable=False),
    sa.Column('resource_id', sa.String(length=40), nullable=True),
    sa.Column('outcome', sa.String(length=24), nullable=False),
    sa.Column('detail', galeqea.models.base.JSONish(), nullable=False),
    sa.Column('model_trace', galeqea.models.base.JSONish(), nullable=True),
    sa.Column('approval_id', sa.String(length=40), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('entry_hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('seq')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_entry_hash'), ['entry_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_id'), ['id'], unique=True)
        batch_op.create_index(batch_op.f('ix_audit_events_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_resource_id'), ['resource_id'], unique=False)

    op.create_table('coverage_snapshots',
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('total_requirements', sa.Integer(), nullable=False),
    sa.Column('covered_requirements', sa.Integer(), nullable=False),
    sa.Column('automated_requirements', sa.Integer(), nullable=False),
    sa.Column('uncovered_refs', galeqea.models.base.JSONish(), nullable=False),
    sa.Column('weak_refs', galeqea.models.base.JSONish(), nullable=False),
    sa.Column('by_risk', galeqea.models.base.JSONish(), nullable=False),
    sa.Column('journey_coverage', galeqea.models.base.JSONish(), nullable=False),
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('coverage_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coverage_snapshots_project_id'), ['project_id'], unique=False)

    op.create_table('exploration_findings',
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('session_id', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=400), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('url', sa.String(length=600), nullable=False),
    sa.Column('reproduction', galeqea.models.base.JSONish(), nullable=False),
    sa.Column('evidence', galeqea.models.base.JSONish(), nullable=False),
    sa.Column('screenshot_path', sa.String(length=1000), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('found_by', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_by', sa.String(length=40), nullable=True),
    sa.Column('promoted_test_id', sa.String(length=40), nullable=True),
    sa.Column('signature', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exploration_findings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exploration_findings_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_exploration_findings_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exploration_findings_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exploration_findings_signature'), ['signature'], unique=False)
        batch_op.create_index(batch_op.f('ix_exploration_findings_status'), ['status'], unique=False)

    op.create_table('exploration_sessions',
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('charter', sa.Text(), nullable=False),
    sa.Column('test_case_id', sa.String(length=40), nullable=True),
    sa.Column('run_id', sa.String(length=40), nullable=True),
    sa.Column('environment', sa.String(length=64), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=False),
    sa.Column('strategy', sa.String(length=24), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('max_steps', sa.Integer(), nullable=False),
    sa.Column('steps_taken', sa.Integer(), nullable=False),
    sa.Column('screens_seen', sa.Integer(), nullable=False),
    sa.Column('trail', galeqea.models.base.JSONish(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('finished_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exploration_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exploration_sessions_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exploration_sessions_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exploration_sessions_status'), ['status'], unique=False)

    op.create_table('failure_signatures',
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('signature', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=400), nullable=False),
    sa.Column('normalized_message', sa.Text(), nullable=False),
    sa.Column('error_type', sa.String(length=80), nullable=False),
    sa.Column('first_seen_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('occurrences', sa.Integer(), nullable=False),
    sa.Column('affected_tests', galeqea.models.base.JSONish(), nullable=False),
    sa.Column('known_issue', sa.Boolean(), nullable=False),
    sa.Column('ticket_ref', sa.String(length=120), nullable=False),
    sa.Column('muted_until', galeqea.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('failure_signatures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_failure_signatures_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_failure_signatures_signature'), ['signature'], unique=False)

    op.create_table('heal_events',
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('element_id', sa.String(length=40), nullable=True),
    sa.Column('test_case_id', sa.String(length=40), nullable=True),
    sa.Column('step_id', sa.String(length=40), nullable=True),
    sa.Column('run_test_id', sa.String(length=40), nullable=True),
    sa.Column('strategy', sa.String(length=32), nullable=False),
    sa.Column('old_locator', sa.Text(), nullable=False),
    sa.Column('new_locator', sa.Text(), nullable=False),
    sa.Column('candidates', galeqea.models.base.JSONish(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('evidence', galeqea.models.base.JSONish(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('used_transiently', sa.Boolean(), nullable=False),
    sa.Column('reviewed_by', sa.String(length=40), nullable=True),
    sa.Column('reviewed_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('heal_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_heal_events_element_id'), ['element_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_heal_events_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_heal_events_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_heal_events_test_case_id'), ['test_case_id'], unique=False)

    op.create_table('integration_connections',
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('provider', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('config', galeqea.models.base.JSONish(), nullable=False),
    sa.Column('secret_refs', galeqea.models.base.JSONish(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('status_detail', sa.Text(), nullable=False),
    sa.Column('last_checked_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('token_cache', galeqea.models.base.JSONish(), nullable=False),
    sa.Column('created_by', sa.String(length=40), nullable=True),
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('integration_connections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_integration_connections_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_integration_connections_provider'), ['provider'], unique=False)

    op.create_table('journeys',
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('target', sa.String(length=2000), nullable=False),
    sa.Column('environment', sa.String(length=64), nullable=False),
    sa.Column('stage', sa.String(length=24), nullable=False),
    sa.Column('completed', galeqea.models.base.JSONish(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('plan_version', sa.Integer(), nullable=False),
    sa.Column('discovery', galeqea.models.base.JSONish(), nullable=False),
    sa.Column('plan', galeqea.models.base.JSONish(), nullable=False),
    sa.Column('test_ids', galeqea.models.base.JSONish(), nullable=False),
    sa.Column('run_id', sa.String(length=40), nullable=True),
    sa.Column('report', galeqea.models.base.JSONish(), nullable=False),
    sa.Column('guardrails', galeqea.models.base.JSONish(), nullable=False),
    sa.Column('created_by', sa.String(length=40), nullable=True),
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('journeys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journeys_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_journeys_stage'), ['stage'], unique=False)
        batch_op.create_index(batch_op.f('ix_journeys_status'), ['status'], unique=False)

    op.create_table('judge_verdicts',
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('run_test_id', sa.String(length=40), nullable=True),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('verdict', sa.String(length=24), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('evidence_refs', galeqea.models.base.JSONish(), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('samples', galeqea.models.base.JSONish(), nullable=False),
    sa.Column('human_override', sa.String(length=24), nullable=False),
    sa.Column('overridden_by', sa.String(length=40), nullable=True),
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('judge_verdicts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_judge_verdicts_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_judge_verdicts_run_test_id'), ['run_test_id'], unique=False)

    op.create_table('memory_items',
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('scope', sa.String(length=32), nullable=False),
    sa.Column('session_id', sa.String(length=40), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=200), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('embedding', galeqea.models.base.JSONish(), nullable=True),
    sa.Column('hits', sa.Integer(), nullable=False),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('expires_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_by_kind', sa.String(length=16), nullable=False),
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('memory_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memory_items_key'), ['key'], unique=False)
        batch_op.create_index(batch_op.f('ix_memory_items_project_id'), ['project_id'], unique=False)

    op.create_table('notifications',
    sa.Column('project_id', sa.String(length=40), nullable=True),
    sa.Column('user_id', sa.String(length=40), nullable=True),
    sa.Column('kind', sa.String(length=48), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('link', sa.String(length=500), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('plugins',
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('manifest', galeqea.models.base.JSONish(), nullable=False),
    sa.Column('entrypoint', sa.String(length=400), nullable=False),
    sa.Column('source_path', sa.String(length=1000), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('granted_permissions', galeqea.models.base.JSONish(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('trusted', sa.Boolean(), nullable=False),
    sa.Column('install_error', sa.Text(), nullable=False),
    sa.Column('load_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plugins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plugins_slug'), ['slug'], unique=True)

    op.create_table('policy_rules',
    sa.Column('project_id', sa.String(length=40), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('matcher', galeqea.models.base.JSONish(), nullable=False),
    sa.Column('effect', sa.String(length=24), nullable=False),
    sa.Column('min_role', sa.String(length=20), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('policy_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_policy_rules_project_id'), ['project_id'], unique=False)

    op.create_table('projects',
    sa.Column('key', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('environments', galeqea.models.base.JSONish(), nullable=False),
    sa.Column('default_environment', sa.String(length=64), nullable=False),
    sa.Column('settings', galeqea.models.base.JSONish(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_key'), ['key'], unique=True)

    op.create_table('rca_reports',
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('run_id', sa.String(length=40), nullable=True),
    sa.Column('run_test_id', sa.String(length=40), nullable=True),
    sa.Column('test_case_id', sa.String(length=40), nullable=True),
    sa.Column('signature', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=48), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('hypotheses', galeqea.models.base.JSONish(), nullable=False),
    sa.Column('evidence', galeqea.models.base.JSONish(), nullable=False),
    sa.Column('suspect_commits', galeqea.models.base.JSONish(), nullable=False),
    sa.Column('suggested_fix', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('generated_by', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('reviewed_by', sa.String(length=40), nullable=True),
    sa.Column('human_verdict', sa.String(length=32), nullable=False),
    sa.Column('ticket_ref', sa.String(length=120), nullable=False),
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rca_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rca_reports_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rca_reports_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rca_reports_run_test_id'), ['run_test_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rca_reports_signature'), ['signature'], unique=False)
        batch_op.create_index(batch_op.f('ix_rca_reports_test_case_id'), ['test_case_id'], unique=False)

    op.create_table('recording_sessions',
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=400), nullable=False),
    sa.Column('environment', sa.String(length=64), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=False),
    sa.Column('start_url', sa.String(length=600), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('stop_reason', sa.String(length=40), nullable=False),
    sa.Column('started_by', sa.String(length=40), nullable=True),
    sa.Column('max_actions', sa.Integer(), nullable=False),
    sa.Column('max_minutes', sa.Integer(), nullable=False),
    sa.Column('actions', galeqea.models.base.JSONish(), nullable=False),
    sa.Column('proposal', galeqea.models.base.JSONish(), nullable=False),
    sa.Column('stats', galeqea.models.base.JSONish(), nullable=False),
    sa.Column('test_case_id', sa.String(length=40), nullable=True),
    sa.Column('finished_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recording_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recording_sessions_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recording_sessions_status'), ['status'], unique=False)

    op.create_table('test_stats',
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('test_case_id', sa.String(length=40), nullable=False),
    sa.Column('runs', sa.Integer(), nullable=False),
    sa.Column('passes', sa.Integer(), nullable=False),
    sa.Column('failures', sa.Integer(), nullable=False),
    sa.Column('errors', sa.Integer(), nullable=False),
    sa.Column('flips', sa.Integer(), nullable=False),
    sa.Column('same_sha_disagreements', sa.Integer(), nullable=False),
    sa.Column('retry_rescues', sa.Integer(), nullable=False),
    sa.Column('flake_score', sa.Float(), nullable=False),
    sa.Column('flake_confidence', sa.Float(), nullable=False),
    sa.Column('flake_reasons', galeqea.models.base.JSONish(), nullable=False),
    sa.Column('mean_duration_ms', sa.Float(), nullable=False),
    sa.Column('m2_duration', sa.Float(), nullable=False),
    sa.Column('p95_duration_ms', sa.Float(), nullable=False),
    sa.Column('duration_samples', galeqea.models.base.JSONish(), nullable=False),
    sa.Column('heal_count', sa.Integer(), nullable=False),
    sa.Column('last_status', sa.String(length=20), nullable=False),
    sa.Column('last_run_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('outcome_window', galeqea.models.base.JSONish(), nullable=False),
    sa.Column('correlated_paths', galeqea.models.base.JSONish(), nullable=False),
    sa.Column('value_score', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('test_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_stats_flake_score'), ['flake_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_stats_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_stats_test_case_id'), ['test_case_id'], unique=True)

    op.create_table('usage_ledger',
    sa.Column('project_id', sa.String(length=40), nullable=True),
    sa.Column('user_id', sa.String(length=40), nullable=True),
    sa.Column('provider', sa.String(length=48), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('agent_role', sa.String(length=48), nullable=False),
    sa.Column('operation', sa.String(length=64), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cached_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('trace_id', sa.String(length=40), nullable=True),
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usage_ledger', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usage_ledger_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_ledger_user_id'), ['user_id'], unique=False)

    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_machine', sa.Boolean(), nullable=False),
    sa.Column('preferences', galeqea.models.base.JSONish(), nullable=False),
    sa.Column('last_seen_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('vault_secrets',
    sa.Column('project_id', sa.String(length=40), nullable=True),
    sa.Column('scope', sa.String(length=48), nullable=False),
    sa.Column('owner_id', sa.String(length=40), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('ciphertext', sa.Text(), nullable=False),
    sa.Column('hint', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=48), nullable=False),
    sa.Column('rotated_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=40), nullable=True),
    sa.Column('meta', galeqea.models.base.JSONish(), nullable=False),
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vault_secrets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vault_secrets_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_vault_secrets_project_id'), ['project_id'], unique=False)

    op.create_table('visual_baselines',
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('screen_id', sa.String(length=40), nullable=True),
    sa.Column('browser', sa.String(length=32), nullable=False),
    sa.Column('viewport', sa.String(length=32), nullable=False),
    sa.Column('image_path', sa.String(length=1000), nullable=False),
    sa.Column('perceptual_hash', sa.String(length=64), nullable=False),
    sa.Column('aria_snapshot', sa.Text(), nullable=False),
    sa.Column('approved_by', sa.String(length=40), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('visual_baselines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visual_baselines_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_visual_baselines_project_id'), ['project_id'], unique=False)

    op.create_table('visual_comparisons',
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('baseline_id', sa.String(length=40), nullable=True),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('run_id', sa.String(length=40), nullable=True),
    sa.Column('run_test_id', sa.String(length=40), nullable=True),
    sa.Column('url', sa.String(length=600), nullable=False),
    sa.Column('browser', sa.String(length=32), nullable=False),
    sa.Column('viewport', sa.String(length=32), nullable=False),
    sa.Column('candidate_path', sa.String(length=1000), nullable=False),
    sa.Column('baseline_path', sa.String(length=1000), nullable=False),
    sa.Column('diff_path', sa.String(length=1000), nullable=False),
    sa.Column('candidate_aria', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('structural', galeqea.models.base.JSONish(), nullable=False),
    sa.Column('regions', galeqea.models.base.JSONish(), nullable=False),
    sa.Column('changed_pct', sa.Float(), nullable=False),
    sa.Column('perceptual_distance', sa.Integer(), nullable=False),
    sa.Column('dimensions_changed', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_by', sa.String(length=40), nullable=True),
    sa.Column('review_comment', sa.Text(), nullable=False),
    sa.Column('judged_by', sa.String(length=24), nullable=False),
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('visual_comparisons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visual_comparisons_baseline_id'), ['baseline_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_visual_comparisons_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_visual_comparisons_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_visual_comparisons_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_visual_comparisons_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_visual_comparisons_status'), ['status'], unique=False)

    op.create_table('webhook_deliveries',
    sa.Column('endpoint_id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('event', sa.String(length=48), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('response_code', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('request_body', sa.Text(), nullable=False),
    sa.Column('delivered_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('webhook_deliveries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhook_deliveries_endpoint_id'), ['endpoint_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_webhook_deliveries_event'), ['event'], unique=False)
        batch_op.create_index(batch_op.f('ix_webhook_deliveries_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_webhook_deliveries_status'), ['status'], unique=False)

    op.create_table('webhook_endpoints',
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('secret', sa.String(length=200), nullable=False),
    sa.Column('events', galeqea.models.base.JSONish(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('created_by', sa.String(length=40), nullable=True),
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('webhook_endpoints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhook_endpoints_project_id'), ['project_id'], unique=False)

    op.create_table('api_tokens',
    sa.Column('user_id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('prefix', sa.String(length=12), nullable=False),
    sa.Column('scopes', galeqea.models.base.JSONish(), nullable=False),
    sa.Column('expires_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_tokens_token_hash'), ['token_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('app_screens',
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('url_pattern', sa.String(length=600), nullable=False),
    sa.Column('route_signature', sa.String(length=200), nullable=False),
    sa.Column('title_pattern', sa.String(length=400), nullable=False),
    sa.Column('aria_signature', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('visit_count', sa.Integer(), nullable=False),
    sa.Column('last_seen_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('embedding', galeqea.models.base.JSONish(), nullable=True),
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('app_screens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_screens_aria_signature'), ['aria_signature'], unique=False)
        batch_op.create_index(batch_op.f('ix_app_screens_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_app_screens_route_signature'), ['route_signature'], unique=False)

    op.create_table('chat_sessions',
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('token_usage', galeqea.models.base.JSONish(), nullable=False),
    sa.Column('context', galeqea.models.base.JSONish(), nullable=False),
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_sessions_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('project_members',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'user_id', name='uq_project_member')
    )
    op.create_table('requirement_docs',
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=400), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('source_filename', sa.String(length=400), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.String(length=40), nullable=True),
    sa.Column('meta', galeqea.models.base.JSONish(), nullable=False),
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('requirement_docs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_requirement_docs_content_sha256'), ['content_sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_requirement_docs_project_id'), ['project_id'], unique=False)

    op.create_table('runs',
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('trigger', sa.String(length=32), nullable=False),
    sa.Column('triggered_by', sa.String(length=40), nullable=True),
    sa.Column('command', sa.Text(), nullable=False),
    sa.Column('environment', sa.String(length=64), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=False),
    sa.Column('browsers', galeqea.models.base.JSONish(), nullable=False),
    sa.Column('suite_id', sa.String(length=40), nullable=True),
    sa.Column('parent_run_id', sa.String(length=40), nullable=True),
    sa.Column('selection', galeqea.models.base.JSONish(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('finished_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('totals', galeqea.models.base.JSONish(), nullable=False),
    sa.Column('triage', galeqea.models.base.JSONish(), nullable=False),
    sa.Column('git_sha', sa.String(length=64), nullable=False),
    sa.Column('git_branch', sa.String(length=200), nullable=False),
    sa.Column('ci_metadata', galeqea.models.base.JSONish(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_runs_number'), ['number'], unique=False)
        batch_op.create_index(batch_op.f('ix_runs_parent_run_id'), ['parent_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_runs_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_runs_status'), ['status'], unique=False)

    op.create_table('schedules',
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('cron', sa.String(length=120), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('suite_id', sa.String(length=40), nullable=True),
    sa.Column('selection', galeqea.models.base.JSONish(), nullable=False),
    sa.Column('environment', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=40), nullable=True),
    sa.Column('last_fired_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('next_fire_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schedules_project_id'), ['project_id'], unique=False)

    op.create_table('test_cases',
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('key', sa.String(length=48), nullable=False),
    sa.Column('title', sa.String(length=400), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('risk', sa.String(length=16), nullable=False),
    sa.Column('tags', galeqea.models.base.JSONish(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('preconditions', galeqea.models.base.JSONish(), nullable=False),
    sa.Column('test_data', galeqea.models.base.JSONish(), nullable=False),
    sa.Column('charter', sa.Text(), nullable=False),
    sa.Column('requirement_refs', galeqea.models.base.JSONish(), nullable=False),
    sa.Column('provenance', galeqea.models.base.JSONish(), nullable=False),
    sa.Column('embedding', galeqea.models.base.JSONish(), nullable=True),
    sa.Column('dedupe_hash', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('approved_by', sa.String(length=40), nullable=True),
    sa.Column('approved_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('review_comment', sa.Text(), nullable=False),
    sa.Column('flake_score', sa.Float(), nullable=False),
    sa.Column('last_status', sa.String(length=20), nullable=False),
    sa.Column('avg_duration_ms', sa.Integer(), nullable=False),
    sa.Column('quarantined', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('test_cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_cases_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_cases_dedupe_hash'), ['dedupe_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_cases_key'), ['key'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_cases_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_cases_status'), ['status'], unique=False)

    op.create_table('test_suites',
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('query', galeqea.models.base.JSONish(), nullable=False),
    sa.Column('parallelism', sa.Integer(), nullable=False),
    sa.Column('browsers', galeqea.models.base.JSONish(), nullable=False),
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('test_suites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_suites_project_id'), ['project_id'], unique=False)

    op.create_table('app_elements',
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('screen_id', sa.String(length=40), nullable=False),
    sa.Column('intent', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=48), nullable=False),
    sa.Column('accessible_name', sa.String(length=400), nullable=False),
    sa.Column('tag', sa.String(length=32), nullable=False),
    sa.Column('locators', galeqea.models.base.JSONish(), nullable=False),
    sa.Column('fingerprint', galeqea.models.base.JSONish(), nullable=False),
    sa.Column('bounding_box', galeqea.models.base.JSONish(), nullable=False),
    sa.Column('embedding', galeqea.models.base.JSONish(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('stability_score', sa.Float(), nullable=False),
    sa.Column('heal_count', sa.Integer(), nullable=False),
    sa.Column('last_verified_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('deprecated', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['screen_id'], ['app_screens.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('app_elements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_elements_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_app_elements_screen_id'), ['screen_id'], unique=False)

    op.create_table('app_transitions',
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('from_screen_id', sa.String(length=40), nullable=False),
    sa.Column('to_screen_id', sa.String(length=40), nullable=False),
    sa.Column('via_element_id', sa.String(length=40), nullable=True),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('observations', sa.Integer(), nullable=False),
    sa.Column('success_rate', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['from_screen_id'], ['app_screens.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_screen_id'], ['app_screens.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('app_transitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_transitions_project_id'), ['project_id'], unique=False)

    op.create_table('chat_messages',
    sa.Column('session_id', sa.String(length=40), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('agent_role', sa.String(length=48), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('blocks', galeqea.models.base.JSONish(), nullable=False),
    sa.Column('tool_calls', galeqea.models.base.JSONish(), nullable=False),
    sa.Column('attachments', galeqea.models.base.JSONish(), nullable=False),
    sa.Column('trace_id', sa.String(length=40), nullable=True),
    sa.Column('usage', galeqea.models.base.JSONish(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_messages_session_id'), ['session_id'], unique=False)

    op.create_table('requirement_items',
    sa.Column('doc_id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('ref', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=400), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('section', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('risk', sa.String(length=16), nullable=False),
    sa.Column('acceptance_criteria', galeqea.models.base.JSONish(), nullable=False),
    sa.Column('open_questions', galeqea.models.base.JSONish(), nullable=False),
    sa.Column('embedding', galeqea.models.base.JSONish(), nullable=True),
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['doc_id'], ['requirement_docs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('requirement_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_requirement_items_doc_id'), ['doc_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_requirement_items_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_requirement_items_ref'), ['ref'], unique=False)

    op.create_table('run_tests',
    sa.Column('run_id', sa.String(length=40), nullable=False),
    sa.Column('test_case_id', sa.String(length=40), nullable=False),
    sa.Column('test_key', sa.String(length=48), nullable=False),
    sa.Column('title', sa.String(length=400), nullable=False),
    sa.Column('browser', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('started_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('finished_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('error_type', sa.String(length=80), nullable=False),
    sa.Column('failure_signature', sa.String(length=64), nullable=False),
    sa.Column('healed', sa.Boolean(), nullable=False),
    sa.Column('classification', sa.String(length=32), nullable=False),
    sa.Column('console_errors', galeqea.models.base.JSONish(), nullable=False),
    sa.Column('network_failures', galeqea.models.base.JSONish(), nullable=False),
    sa.Column('metrics', galeqea.models.base.JSONish(), nullable=False),
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('run_tests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_run_tests_failure_signature'), ['failure_signature'], unique=False)
        batch_op.create_index(batch_op.f('ix_run_tests_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_run_tests_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_run_tests_test_case_id'), ['test_case_id'], unique=False)

    op.create_table('suite_members',
    sa.Column('suite_id', sa.String(length=40), nullable=False),
    sa.Column('test_case_id', sa.String(length=40), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['suite_id'], ['test_suites.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('suite_id', 'test_case_id', name='uq_suite_member')
    )
    op.create_table('test_steps',
    sa.Column('test_case_id', sa.String(length=40), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('intent', sa.Text(), nullable=False),
    sa.Column('expected', sa.Text(), nullable=False),
    sa.Column('target', galeqea.models.base.JSONish(), nullable=False),
    sa.Column('element_id', sa.String(length=40), nullable=True),
    sa.Column('value', galeqea.models.base.JSONish(), nullable=False),
    sa.Column('options', galeqea.models.base.JSONish(), nullable=False),
    sa.Column('timeout_ms', sa.Integer(), nullable=True),
    sa.Column('optional', sa.Boolean(), nullable=False),
    sa.Column('continue_on_failure', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('test_steps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_steps_element_id'), ['element_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_steps_test_case_id'), ['test_case_id'], unique=False)

    op.create_table('test_versions',
    sa.Column('test_case_id', sa.String(length=40), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('snapshot', galeqea.models.base.JSONish(), nullable=False),
    sa.Column('change_summary', sa.Text(), nullable=False),
    sa.Column('author_kind', sa.String(length=16), nullable=False),
    sa.Column('author_id', sa.String(length=40), nullable=True),
    sa.Column('approved_by', sa.String(length=40), nullable=True),
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('test_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_versions_test_case_id'), ['test_case_id'], unique=False)

    op.create_table('run_steps',
    sa.Column('run_test_id', sa.String(length=40), nullable=False),
    sa.Column('step_id', sa.String(length=40), nullable=True),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('intent', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('resolved_locator', sa.Text(), nullable=False),
    sa.Column('heal_applied', galeqea.models.base.JSONish(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('logs', galeqea.models.base.JSONish(), nullable=False),
    sa.Column('artifacts', galeqea.models.base.JSONish(), nullable=False),
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['run_test_id'], ['run_tests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('run_steps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_run_steps_run_test_id'), ['run_test_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('run_steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_run_steps_run_test_id'))

    op.drop_table('run_steps')
    with op.batch_alter_table('test_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_versions_test_case_id'))

    op.drop_table('test_versions')
    with op.batch_alter_table('test_steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_steps_test_case_id'))
        batch_op.drop_index(batch_op.f('ix_test_steps_element_id'))

    op.drop_table('test_steps')
    op.drop_table('suite_members')
    with op.batch_alter_table('run_tests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_run_tests_test_case_id'))
        batch_op.drop_index(batch_op.f('ix_run_tests_status'))
        batch_op.drop_index(batch_op.f('ix_run_tests_run_id'))
        batch_op.drop_index(batch_op.f('ix_run_tests_failure_signature'))

    op.drop_table('run_tests')
    with op.batch_alter_table('requirement_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_requirement_items_ref'))
        batch_op.drop_index(batch_op.f('ix_requirement_items_project_id'))
        batch_op.drop_index(batch_op.f('ix_requirement_items_doc_id'))

    op.drop_table('requirement_items')
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_messages_session_id'))

    op.drop_table('chat_messages')
    with op.batch_alter_table('app_transitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_transitions_project_id'))

    op.drop_table('app_transitions')
    with op.batch_alter_table('app_elements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_elements_screen_id'))
        batch_op.drop_index(batch_op.f('ix_app_elements_project_id'))

    op.drop_table('app_elements')
    with op.batch_alter_table('test_suites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_suites_project_id'))

    op.drop_table('test_suites')
    with op.batch_alter_table('test_cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_cases_status'))
        batch_op.drop_index(batch_op.f('ix_test_cases_project_id'))
        batch_op.drop_index(batch_op.f('ix_test_cases_key'))
        batch_op.drop_index(batch_op.f('ix_test_cases_dedupe_hash'))
        batch_op.drop_index(batch_op.f('ix_test_cases_category'))

    op.drop_table('test_cases')
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedules_project_id'))

    op.drop_table('schedules')
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_runs_status'))
        batch_op.drop_index(batch_op.f('ix_runs_project_id'))
        batch_op.drop_index(batch_op.f('ix_runs_parent_run_id'))
        batch_op.drop_index(batch_op.f('ix_runs_number'))

    op.drop_table('runs')
    with op.batch_alter_table('requirement_docs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_requirement_docs_project_id'))
        batch_op.drop_index(batch_op.f('ix_requirement_docs_content_sha256'))

    op.drop_table('requirement_docs')
    op.drop_table('project_members')
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_chat_sessions_project_id'))

    op.drop_table('chat_sessions')
    with op.batch_alter_table('app_screens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_screens_route_signature'))
        batch_op.drop_index(batch_op.f('ix_app_screens_project_id'))
        batch_op.drop_index(batch_op.f('ix_app_screens_aria_signature'))

    op.drop_table('app_screens')
    with op.batch_alter_table('api_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_api_tokens_token_hash'))

    op.drop_table('api_tokens')
    with op.batch_alter_table('webhook_endpoints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhook_endpoints_project_id'))

    op.drop_table('webhook_endpoints')
    with op.batch_alter_table('webhook_deliveries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhook_deliveries_status'))
        batch_op.drop_index(batch_op.f('ix_webhook_deliveries_project_id'))
        batch_op.drop_index(batch_op.f('ix_webhook_deliveries_event'))
        batch_op.drop_index(batch_op.f('ix_webhook_deliveries_endpoint_id'))

    op.drop_table('webhook_deliveries')
    with op.batch_alter_table('visual_comparisons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visual_comparisons_status'))
        batch_op.drop_index(batch_op.f('ix_visual_comparisons_severity'))
        batch_op.drop_index(batch_op.f('ix_visual_comparisons_run_id'))
        batch_op.drop_index(batch_op.f('ix_visual_comparisons_project_id'))
        batch_op.drop_index(batch_op.f('ix_visual_comparisons_name'))
        batch_op.drop_index(batch_op.f('ix_visual_comparisons_baseline_id'))

    op.drop_table('visual_comparisons')
    with op.batch_alter_table('visual_baselines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visual_baselines_project_id'))
        batch_op.drop_index(batch_op.f('ix_visual_baselines_name'))

    op.drop_table('visual_baselines')
    with op.batch_alter_table('vault_secrets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vault_secrets_project_id'))
        batch_op.drop_index(batch_op.f('ix_vault_secrets_name'))

    op.drop_table('vault_secrets')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('usage_ledger', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usage_ledger_user_id'))
        batch_op.drop_index(batch_op.f('ix_usage_ledger_project_id'))

    op.drop_table('usage_ledger')
    with op.batch_alter_table('test_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_stats_test_case_id'))
        batch_op.drop_index(batch_op.f('ix_test_stats_project_id'))
        batch_op.drop_index(batch_op.f('ix_test_stats_flake_score'))

    op.drop_table('test_stats')
    with op.batch_alter_table('recording_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recording_sessions_status'))
        batch_op.drop_index(batch_op.f('ix_recording_sessions_project_id'))

    op.drop_table('recording_sessions')
    with op.batch_alter_table('rca_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rca_reports_test_case_id'))
        batch_op.drop_index(batch_op.f('ix_rca_reports_signature'))
        batch_op.drop_index(batch_op.f('ix_rca_reports_run_test_id'))
        batch_op.drop_index(batch_op.f('ix_rca_reports_run_id'))
        batch_op.drop_index(batch_op.f('ix_rca_reports_project_id'))

    op.drop_table('rca_reports')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_key'))

    op.drop_table('projects')
    with op.batch_alter_table('policy_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_policy_rules_project_id'))

    op.drop_table('policy_rules')
    with op.batch_alter_table('plugins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plugins_slug'))

    op.drop_table('plugins')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_project_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('memory_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memory_items_project_id'))
        batch_op.drop_index(batch_op.f('ix_memory_items_key'))

    op.drop_table('memory_items')
    with op.batch_alter_table('judge_verdicts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_judge_verdicts_run_test_id'))
        batch_op.drop_index(batch_op.f('ix_judge_verdicts_project_id'))

    op.drop_table('judge_verdicts')
    with op.batch_alter_table('journeys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journeys_status'))
        batch_op.drop_index(batch_op.f('ix_journeys_stage'))
        batch_op.drop_index(batch_op.f('ix_journeys_project_id'))

    op.drop_table('journeys')
    with op.batch_alter_table('integration_connections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_integration_connections_provider'))
        batch_op.drop_index(batch_op.f('ix_integration_connections_project_id'))

    op.drop_table('integration_connections')
    with op.batch_alter_table('heal_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_heal_events_test_case_id'))
        batch_op.drop_index(batch_op.f('ix_heal_events_status'))
        batch_op.drop_index(batch_op.f('ix_heal_events_project_id'))
        batch_op.drop_index(batch_op.f('ix_heal_events_element_id'))

    op.drop_table('heal_events')
    with op.batch_alter_table('failure_signatures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_failure_signatures_signature'))
        batch_op.drop_index(batch_op.f('ix_failure_signatures_project_id'))

    op.drop_table('failure_signatures')
    with op.batch_alter_table('exploration_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exploration_sessions_status'))
        batch_op.drop_index(batch_op.f('ix_exploration_sessions_run_id'))
        batch_op.drop_index(batch_op.f('ix_exploration_sessions_project_id'))

    op.drop_table('exploration_sessions')
    with op.batch_alter_table('exploration_findings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exploration_findings_status'))
        batch_op.drop_index(batch_op.f('ix_exploration_findings_signature'))
        batch_op.drop_index(batch_op.f('ix_exploration_findings_session_id'))
        batch_op.drop_index(batch_op.f('ix_exploration_findings_project_id'))
        batch_op.drop_index(batch_op.f('ix_exploration_findings_kind'))

    op.drop_table('exploration_findings')
    with op.batch_alter_table('coverage_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coverage_snapshots_project_id'))

    op.drop_table('coverage_snapshots')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_resource_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_project_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_entry_hash'))
        batch_op.drop_index(batch_op.f('ix_audit_events_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_events_actor_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_action'))

    op.drop_table('audit_events')
    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artifacts_run_test_id'))
        batch_op.drop_index(batch_op.f('ix_artifacts_run_id'))

    op.drop_table('artifacts')
    with op.batch_alter_table('approval_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approval_requests_status'))
        batch_op.drop_index(batch_op.f('ix_approval_requests_risk'))
        batch_op.drop_index(batch_op.f('ix_approval_requests_project_id'))
        batch_op.drop_index(batch_op.f('ix_approval_requests_batch_id'))
        batch_op.drop_index(batch_op.f('ix_approval_requests_action'))

    op.drop_table('approval_requests')
    with op.batch_alter_table('approval_batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approval_batches_status'))
        batch_op.drop_index(batch_op.f('ix_approval_batches_project_id'))

    op.drop_table('approval_batches')
    with op.batch_alter_table('anomaly_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_anomaly_records_run_id'))
        batch_op.drop_index(batch_op.f('ix_anomaly_records_project_id'))

    op.drop_table('anomaly_records')
    with op.batch_alter_table('agent_traces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_traces_session_id'))
        batch_op.drop_index(batch_op.f('ix_agent_traces_project_id'))

    op.drop_table('agent_traces')
    # ### end Alembic commands ###
