"""test manager core entities

Revision ID: 63d03d307909
Revises: 42c3921c27bf
Create Date: 2026-08-29 11:47:27.734775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import galeqea.models.base


# revision identifiers, used by Alembic.
revision: str = '63d03d307909'
down_revision: Union[str, Sequence[str], None] = '42c3921c27bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('defect_links',
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('result_id', sa.String(length=40), nullable=True),
    sa.Column('test_case_id', sa.String(length=40), nullable=True),
    sa.Column('tracker', sa.String(length=16), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('url', sa.String(length=600), nullable=False),
    sa.Column('status_cached', sa.String(length=60), nullable=False),
    sa.Column('last_synced', galeqea.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('defect_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_defect_links_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_defect_links_result_id'), ['result_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_defect_links_test_case_id'), ['test_case_id'], unique=False)

    op.create_table('environments',
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=False),
    sa.Column('build_label', sa.String(length=120), nullable=False),
    sa.Column('credentials_ref', sa.String(length=120), nullable=True),
    sa.Column('tags', galeqea.models.base.JSONish(), nullable=False),
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('environments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_environments_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_environments_project_id'), ['project_id'], unique=False)

    op.create_table('milestones',
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('target_date', galeqea.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('exit_criteria', galeqea.models.base.JSONish(), nullable=False),
    sa.Column('signoff', galeqea.models.base.JSONish(), nullable=False),
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('milestones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_milestones_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_milestones_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_milestones_version'), ['version'], unique=False)

    op.create_table('shared_steps',
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('steps', galeqea.models.base.JSONish(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shared_steps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shared_steps_project_id'), ['project_id'], unique=False)

    op.create_table('test_plans',
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('milestone_id', sa.String(length=40), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('selection', galeqea.models.base.JSONish(), nullable=False),
    sa.Column('configurations', galeqea.models.base.JSONish(), nullable=False),
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestones.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('test_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_plans_milestone_id'), ['milestone_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_plans_project_id'), ['project_id'], unique=False)

    op.create_table('cycles',
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('plan_id', sa.String(length=40), nullable=False),
    sa.Column('milestone_id', sa.String(length=40), nullable=True),
    sa.Column('environment_id', sa.String(length=40), nullable=True),
    sa.Column('name', sa.String(length=240), nullable=False),
    sa.Column('configuration', galeqea.models.base.JSONish(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('pinned_cases', galeqea.models.base.JSONish(), nullable=False),
    sa.Column('counters', galeqea.models.base.JSONish(), nullable=False),
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestones.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['plan_id'], ['test_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cycles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cycles_environment_id'), ['environment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cycles_milestone_id'), ['milestone_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cycles_plan_id'), ['plan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cycles_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cycles_status'), ['status'], unique=False)

    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cycle_id', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('milestone_id', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('environment_id', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('environment_snapshot', galeqea.models.base.JSONish(), nullable=False, server_default='{}'))
        batch_op.create_index(batch_op.f('ix_runs_cycle_id'), ['cycle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_runs_environment_id'), ['environment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_runs_milestone_id'), ['milestone_id'], unique=False)

    with op.batch_alter_table('test_cases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shared_step_ids', galeqea.models.base.JSONish(), nullable=False, server_default='[]'))
        batch_op.add_column(sa.Column('parameters', galeqea.models.base.JSONish(), nullable=False, server_default='{}'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_cases', schema=None) as batch_op:
        batch_op.drop_column('parameters')
        batch_op.drop_column('shared_step_ids')

    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_runs_milestone_id'))
        batch_op.drop_index(batch_op.f('ix_runs_environment_id'))
        batch_op.drop_index(batch_op.f('ix_runs_cycle_id'))
        batch_op.drop_column('environment_snapshot')
        batch_op.drop_column('environment_id')
        batch_op.drop_column('milestone_id')
        batch_op.drop_column('cycle_id')

    with op.batch_alter_table('cycles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cycles_status'))
        batch_op.drop_index(batch_op.f('ix_cycles_project_id'))
        batch_op.drop_index(batch_op.f('ix_cycles_plan_id'))
        batch_op.drop_index(batch_op.f('ix_cycles_milestone_id'))
        batch_op.drop_index(batch_op.f('ix_cycles_environment_id'))

    op.drop_table('cycles')
    with op.batch_alter_table('test_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_plans_project_id'))
        batch_op.drop_index(batch_op.f('ix_test_plans_milestone_id'))

    op.drop_table('test_plans')
    with op.batch_alter_table('shared_steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shared_steps_project_id'))

    op.drop_table('shared_steps')
    with op.batch_alter_table('milestones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_milestones_version'))
        batch_op.drop_index(batch_op.f('ix_milestones_status'))
        batch_op.drop_index(batch_op.f('ix_milestones_project_id'))

    op.drop_table('milestones')
    with op.batch_alter_table('environments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_environments_project_id'))
        batch_op.drop_index(batch_op.f('ix_environments_name'))

    op.drop_table('environments')
    with op.batch_alter_table('defect_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_defect_links_test_case_id'))
        batch_op.drop_index(batch_op.f('ix_defect_links_result_id'))
        batch_op.drop_index(batch_op.f('ix_defect_links_project_id'))

    op.drop_table('defect_links')
    # ### end Alembic commands ###
