"""defect map for failure dedupe

Revision ID: da97ca2015c5
Revises: 219069176a96
Create Date: 2026-08-29 12:42:45.409634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import galeqea.models.base


# revision identifiers, used by Alembic.
revision: str = 'da97ca2015c5'
down_revision: Union[str, Sequence[str], None] = '219069176a96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('defect_maps',
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('failure_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('issue_key', sa.String(length=120), nullable=False),
    sa.Column('issue_id', sa.String(length=64), nullable=False),
    sa.Column('url', sa.String(length=600), nullable=False),
    sa.Column('status_cached', sa.String(length=60), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('reopened_count', sa.Integer(), nullable=False),
    sa.Column('first_seen', galeqea.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('last_seen', galeqea.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('last_synced', galeqea.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', galeqea.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'provider', 'failure_fingerprint', name='uq_defect_map_fingerprint')
    )
    with op.batch_alter_table('defect_maps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_defect_maps_failure_fingerprint'), ['failure_fingerprint'], unique=False)
        batch_op.create_index(batch_op.f('ix_defect_maps_project_id'), ['project_id'], unique=False)
    # NOTE: alembic autogen also proposed dropping the milestones
    # `uq_milestone_project_version` partial index — that is a false positive
    # (autogen cannot round-trip a partial/`WHERE` index). Removed by hand so this
    # migration leaves the WO#5 one-live-milestone-per-version guard intact.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    with op.batch_alter_table('defect_maps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_defect_maps_project_id'))
        batch_op.drop_index(batch_op.f('ix_defect_maps_failure_fingerprint'))

    op.drop_table('defect_maps')
