"""The typed test plan: every kind of test, proposed as a reviewable row.

A plan is the review board: for a discovered site it proposes rows across every
test type a QE team cares about (functional, forms, links, API, accessibility,
performance, visual, responsive, cross-browser, security, SEO, resilience,
data-driven, exploratory, manual), each carrying a count, risk, confidence, and
an estimate of run-minutes and *build* tokens (0 when the type is deterministic /
model-free). Rows are toggleable; editing produces a new plan version with a diff.

Everything is derived deterministically from the discovery, so the same site
proposes the same plan. A model, when present, only sharpens wording; it never
invents the numbers.
"""

from __future__ import annotations

#: Per-type authoring/run cost model. `tokens` is the model cost to *author* the
#: type's tests once (0 for types generated by rule); re-runs always cost 0.
_TYPES: list[dict] = [
    # key, label, category, risk, confidence, min_per, tokens_per, default_on, count_fn
    {"key": "functional", "label": "Functional / E2E", "category": "functional",
     "risk": "high", "confidence": "High", "min_per": 0.4, "tokens_per": 0, "on": True,
     "count": lambda d: len(d["pages"]),
     "why": "every page loads and renders, primary navigation resolves"},
    {"key": "forms", "label": "Forms: negative & boundary", "category": "functional",
     "risk": "high", "confidence": "Med", "min_per": 0.5, "tokens_per": 2500, "on": True,
     "count": lambda d: max(0, d.get("forms", 0)) * 3,
     "why": "required / min-max / pattern / type violations per field (BVA + EP)"},
    {"key": "links", "label": "Links & navigation", "category": "functional",
     "risk": "medium", "confidence": "High", "min_per": 1.0, "tokens_per": 0, "on": True,
     "count": lambda d: 1,
     "why": "internal links resolve (no 4xx), anchors, redirects, off-site flagged"},
    {"key": "api", "label": "API / contract", "category": "functional",
     "risk": "high", "confidence": "Low", "min_per": 0.5, "tokens_per": 2000, "on": False,
     "count": lambda d: len(d.get("apis") or []),
     "why": "observed XHR/fetch endpoints: status + JSON-shape (OpenAPI if found)"},
    {"key": "a11y", "label": "Accessibility (axe, WCAG 2.2 AA)", "category": "non_functional",
     "risk": "high", "confidence": "High", "min_per": 0.5, "tokens_per": 0, "on": True,
     "count": lambda d: len(d["pages"]),
     "why": "axe per page + keyboard reachability of form controls"},
    {"key": "perf", "label": "Performance (Core Web Vitals)", "category": "non_functional",
     "risk": "medium", "confidence": "Med", "min_per": 0.6, "tokens_per": 0, "on": True,
     "count": lambda d: len(d["pages"]),
     "why": "LCP / CLS / TTFB budgets, page weight, slow requests"},
    {"key": "visual", "label": "Visual snapshots (desktop + mobile)", "category": "non_functional",
     "risk": "medium", "confidence": "Med", "min_per": 0.3, "tokens_per": 0, "on": False,
     "count": lambda d: len(d["pages"]) * 2,
     "why": "baseline snapshot per page at two widths; diffs on re-run"},
    {"key": "responsive", "label": "Responsive viewports", "category": "non_functional",
     "risk": "medium", "confidence": "Med", "min_per": 0.3, "tokens_per": 0, "on": False,
     "count": lambda d: len(d["pages"]) * 3,
     "why": "mobile 390×844, tablet 820×1180, desktop 1440×900"},
    {"key": "cross_browser", "label": "Cross-browser", "category": "non_functional",
     "risk": "medium", "confidence": "Med", "min_per": 0.5, "tokens_per": 0, "on": False,
     "count": lambda d: len(d["pages"]),
     "why": "chromium by default; firefox / webkit as toggles"},
    {"key": "security", "label": "Security hygiene", "category": "non_functional",
     "risk": "high", "confidence": "High", "min_per": 1.0, "tokens_per": 0, "on": True,
     "count": lambda d: 1,
     "why": "HTTPS, HSTS/CSP/X-Frame/X-Content-Type, mixed content, cookie flags, exposed .env/.git, secret-looking strings"},
    {"key": "seo", "label": "SEO / hygiene", "category": "non_functional",
     "risk": "low", "confidence": "High", "min_per": 0.2, "tokens_per": 0, "on": True,
     "count": lambda d: len(d["pages"]),
     "why": "title / meta / canonical / robots / sitemap / broken images / console errors"},
    {"key": "resilience", "label": "Resilience (offline, slow-3G, 5xx)", "category": "non_functional",
     "risk": "medium", "confidence": "Low", "min_per": 1.0, "tokens_per": 0, "on": False,
     "count": lambda d: 3,
     "why": "network throttling and forced API 5xx: the page still renders an error state, not a blank screen"},
    {"key": "data_driven", "label": "Data-driven (parameter rows)", "category": "functional",
     "risk": "low", "confidence": "Med", "min_per": 0.3, "tokens_per": 1500, "on": False,
     "count": lambda d: max(0, d.get("forms", 0)),
     "why": "a table of valid/invalid rows per form field"},
    {"key": "exploratory", "label": "Exploratory charters", "category": "manual",
     "risk": "medium", "confidence": "Low", "min_per": 10.0, "tokens_per": 0, "on": False,
     "count": lambda d: max(1, len(d["pages"]) // 5),
     "why": "a session-based charter per section, for a human (or the agent) to poke at"},
    {"key": "manual", "label": "Manual checks", "category": "manual",
     "risk": "medium", "confidence": "High", "min_per": 5.0, "tokens_per": 0, "on": False,
     "count": lambda d: 2,
     "why": "things that can't be automated (email receipt, real payment) as a checklist"},
]

_RISK_ORDER = {"critical": 0, "high": 1, "medium": 2, "low": 3}

#: The set of known golden-path type keys, and a short human label for each. This
#: is the single source of truth for "what type is this test": the report table,
#: the run board bars, the JUnit testsuite names, and the readiness rules all
#: resolve type through :func:`golden_path_type` / :func:`type_label`, so they can
#: never disagree.
TYPE_KEYS: frozenset[str] = frozenset(spec["key"] for spec in _TYPES)
_TYPE_LABEL: dict[str, str] = {
    "functional": "Functional", "forms": "Forms", "links": "Links", "api": "API",
    "a11y": "Accessibility", "perf": "Performance", "visual": "Visual",
    "responsive": "Responsive", "cross_browser": "Cross-browser", "security": "Security",
    "seo": "SEO", "resilience": "Resilience", "data_driven": "Data-driven",
    "exploratory": "Exploratory", "manual": "Manual", "login": "Login",
}
#: Types whose failures block a release verdict outright (a security hole or a
#: serious accessibility barrier is not a "review", it's a "not ready").
CRITICAL_TYPES: frozenset[str] = frozenset({"security", "a11y"})


def type_from_key(key: str) -> str | None:
    """The type token embedded in a golden-path key `{PROJ}-GP-{TYPE}-{NN}`."""
    if "-GP-" not in (key or ""):
        return None
    token = key.split("-GP-", 1)[1].split("-", 1)[0].lower()
    # Keys strip underscores; map the compacted tokens back.
    return {"crossbrowser": "cross_browser", "datadriven": "data_driven"}.get(token, token)


def golden_path_type(case=None, key: str = "") -> str:
    """The one true test type for a case: its ``provenance.type``, else a known
    type in its tags, else the token in its key, else its category. Every surface
    that groups by type must go through here."""
    if case is not None:
        prov = getattr(case, "provenance", None) or {}
        if prov.get("type"):
            return prov["type"]
        for tag in (getattr(case, "tags", None) or []):
            if tag in TYPE_KEYS:
                return tag
        key = key or getattr(case, "key", "") or ""
    from_key = type_from_key(key)
    if from_key:
        return from_key
    if case is not None:
        return getattr(case, "category", None) or "functional"
    return "functional"


def type_label(type_key: str) -> str:
    return _TYPE_LABEL.get(type_key, type_key.replace("_", " ").title())


def _normalize(discovery: dict) -> dict:
    """Canonicalise the discovery so a count function can rely on shapes: `pages`
    and `apis` are lists, `forms` is an int, whether the caller passed a list, an
    int, or nothing. This keeps the count rules simple and crash-proof."""
    def as_list(v):
        if isinstance(v, (list, tuple)):
            return list(v)
        return [None] * max(0, int(v or 0))

    def as_int(v):
        if isinstance(v, (list, tuple)):
            return len(v)
        return max(0, int(v or 0))

    return {
        **discovery,
        "pages": as_list(discovery.get("pages")) or [None],
        "apis": as_list(discovery.get("apis")),
        "forms": as_int(discovery.get("forms")),
    }


def build_typed_plan(discovery: dict, *, version: int = 1, enabled: dict | None = None) -> dict:
    """The full plan: one row per test type, with counts and estimates. `enabled`
    (a {key: bool} override) lets a caller carry toggles across versions. The
    discovery shape is normalised first, so `forms`/`apis` may be a list or a count."""
    d = _normalize(discovery)
    rows = []
    for spec in _TYPES:
        count = int(spec["count"](d))
        if count <= 0 and spec["key"] in {"forms", "api", "data_driven"}:
            continue  # nothing to test of this type on this site
        on = enabled.get(spec["key"], spec["on"]) if enabled else spec["on"]
        rows.append({
            "key": spec["key"], "label": spec["label"], "category": spec["category"],
            "count": count, "risk": spec["risk"], "confidence": spec["confidence"],
            "est_minutes": round(count * spec["min_per"], 1),
            "est_tokens": (count * spec["tokens_per"]) if on else 0,
            "rerun_tokens": 0,
            "enabled": bool(on),
            "why": spec["why"],
        })
    rows.sort(key=lambda r: (not r["enabled"], _RISK_ORDER.get(r["risk"], 9), r["key"]))
    return {
        "version": version,
        "target": discovery.get("base", ""),
        "types": rows,
        "totals": _totals(rows),
    }


def _totals(rows: list[dict]) -> dict:
    active = [r for r in rows if r["enabled"]]
    return {
        "types_enabled": len(active),
        "types_total": len(rows),
        "test_count": sum(r["count"] for r in active),
        "est_minutes": round(sum(r["est_minutes"] for r in active), 1),
        "est_build_tokens": sum(r["est_tokens"] for r in active),
        "rerun_tokens": 0,
    }


def toggle(plan: dict, key: str, on: bool) -> dict:
    """Return a new plan version with one type flipped on/off. Counts are kept from
    the stored plan (no re-crawl); only enablement, build tokens and totals move."""
    rows = []
    for r in plan["types"]:
        active = on if r["key"] == key else r["enabled"]
        rows.append({**r, "enabled": active, "est_tokens": _rate_tokens(r) if active else 0})
    rows.sort(key=lambda r: (not r["enabled"], _RISK_ORDER.get(r["risk"], 9), r["key"]))
    return {"version": plan["version"] + 1, "target": plan["target"],
            "types": rows, "totals": _totals(rows)}


def _rate_tokens(row: dict) -> int:
    spec = next((s for s in _TYPES if s["key"] == row["key"]), None)
    return int(row["count"] * spec["tokens_per"]) if spec else 0


def diff(old: dict, new: dict) -> list[str]:
    """A human diff between two plan versions: what turned on/off or changed."""
    before = {r["key"]: r for r in old.get("types", [])}
    after = {r["key"]: r for r in new.get("types", [])}
    lines = []
    for key, r in after.items():
        was = before.get(key)
        if was is None:
            lines.append(f"+ added {r['label']}")
        elif was["enabled"] != r["enabled"]:
            lines.append(f"{'+ enabled' if r['enabled'] else '- disabled'} {r['label']}")
    for key, r in before.items():
        if key not in after:
            lines.append(f"- removed {r['label']}")
    return lines


def plan_markdown(plan: dict) -> str:
    """The plan as a versioned Markdown artifact."""
    t = plan["totals"]
    lines = [
        f"# Test plan v{plan['version']}: {plan['target']}",
        "",
        f"**{t['types_enabled']} test type(s), {t['test_count']} test(s), "
        f"~{t['est_minutes']} min, ~{t['est_build_tokens']:,} build tokens** "
        "(re-runs cost 0).",
        "",
        "| Type | Tests | Risk | Confidence | Min | Build tokens | On |",
        "| --- | --- | --- | --- | --- | --- | --- |",
    ]
    for r in plan["types"]:
        lines.append(
            f"| {r['label']} | {r['count']} | {r['risk']} | {r['confidence']} | "
            f"{r['est_minutes']} | {r['est_tokens']:,} | {'✓' if r['enabled'] else '·'} |"
        )
    return "\n".join(lines) + "\n"
