"""Render stored tests into runnable source code.

Zero lock-in is a design goal, not a slogan: a team must be able to take their
tests and leave. Because tests are stored as structured steps rather than as
code, exporting to Playwright TypeScript, Playwright Python, pytest, Robot
Framework or Gherkin is a rendering problem, and the exported file is a normal
test that runs with no GaleQEA dependency at all.
"""

from __future__ import annotations

from ..models import StepAction, TestCase, TestStep

TARGETS = ("playwright", "playwright_python", "pytest", "robot", "cucumber")


def render(case: TestCase, *, target: str = "playwright", base_url: str = "") -> str:
    if target not in TARGETS:
        raise ValueError(f"unknown export target {target!r}; supported: {', '.join(TARGETS)}")
    steps = sorted(case.steps, key=lambda s: s.index)
    return {
        "playwright": _playwright_ts,
        "playwright_python": _playwright_py,
        "pytest": _playwright_py,
        "robot": _robot,
        "cucumber": _cucumber,
    }[target](case, steps, base_url)


# --------------------------------------------------------------------------- #
def _locator_ts(step: TestStep) -> str:
    ladder = (step.target or {}).get("ladder") or []
    if not ladder:
        role = (step.target or {}).get("role")
        name = (step.target or {}).get("accessible_name")
        if role and name:
            return f"page.getByRole('{role}', {{ name: {_q(name)} }})"
        return "page.locator('body')"
    rung = ladder[0]
    kind = rung.get("kind")
    if kind == "role":
        name = rung.get("name")
        return (f"page.getByRole('{rung.get('role')}'"
                + (f", {{ name: {_q(name)} }}" if name else "") + ")")
    if kind == "testid":
        return f"page.getByTestId({_q(rung.get('value', ''))})"
    if kind in {"label", "placeholder", "text", "alt", "title"}:
        method = {"label": "getByLabel", "placeholder": "getByPlaceholder", "text": "getByText",
                  "alt": "getByAltText", "title": "getByTitle"}[kind]
        return f"page.{method}({_q(rung.get('value', ''))})"
    if kind == "xpath":
        return f"page.locator('xpath={rung.get('value', '')}')"
    return f"page.locator({_q(rung.get('value', ''))})"


def _playwright_ts(case: TestCase, steps: list[TestStep], base_url: str) -> str:
    lines = [
        "// Generated by GaleQEA. This file has no GaleQEA dependency - it is a",
        "// standard Playwright test you can run, edit and keep.",
        f"// Source test: {case.key} — {case.title}",
        f"// Requirements: {', '.join(case.requirement_refs) or 'none recorded'}",
        "",
        "import { test, expect } from '@playwright/test';",
        "",
        f"test({_q(f'{case.key} {case.title}')}, async ({{ page }}) => {{",
    ]
    for pre in case.preconditions or []:
        lines.append(f"  // Precondition: {pre}")

    for step in steps:
        loc = _locator_ts(step)
        value = step.value or {}
        text = value.get("text", "")
        lines.append(f"  // {step.intent}" if step.intent else "")
        match step.action:
            case StepAction.GOTO:
                url = value.get("url", "/")
                full = url if url.startswith("http") else f"{base_url.rstrip('/')}{url}"
                lines.append(f"  await page.goto({_q(full)});")
            case StepAction.CLICK:
                lines.append(f"  await {loc}.click();")
            case StepAction.DOUBLE_CLICK:
                lines.append(f"  await {loc}.dblclick();")
            case StepAction.FILL:
                lines.append(f"  await {loc}.fill({_q(text)});")
            case StepAction.TYPE:
                lines.append(f"  await {loc}.pressSequentially({_q(text)});")
            case StepAction.PRESS:
                lines.append(f"  await {loc}.press({_q(value.get('key', 'Enter'))});")
            case StepAction.SELECT:
                lines.append(f"  await {loc}.selectOption({_q(text)});")
            case StepAction.CHECK:
                lines.append(f"  await {loc}.check();")
            case StepAction.UNCHECK:
                lines.append(f"  await {loc}.uncheck();")
            case StepAction.HOVER:
                lines.append(f"  await {loc}.hover();")
            case StepAction.EXPECT_VISIBLE:
                lines.append(f"  await expect({loc}).toBeVisible();")
            case StepAction.EXPECT_TEXT:
                lines.append(f"  await expect({loc}).toContainText({_q(text)});")
            case StepAction.EXPECT_VALUE:
                lines.append(f"  await expect({loc}).toHaveValue({_q(text)});")
            case StepAction.EXPECT_URL:
                lines.append(f"  await expect(page).toHaveURL(/{_re(value.get('url', ''))}/);")
            case StepAction.EXPECT_COUNT:
                lines.append(f"  await expect({loc}).toHaveCount({value.get('count', 1)});")
            case StepAction.EXPECT_ATTRIBUTE:
                lines.append(
                    f"  await expect({loc}).toHaveAttribute("
                    f"{_q(value.get('attribute', ''))}, {_q(text)});"
                )
            case StepAction.WAIT_FOR:
                lines.append(f"  await {loc}.waitFor({{ state: 'visible' }});")
            case StepAction.SNAPSHOT:
                lines.append(
                    f"  await expect(page).toHaveScreenshot({_q(value.get('name', case.key) + '.png')});"
                )
            case StepAction.EXPECT_SEMANTIC:
                lines.append(
                    f"  // Semantic assertion (GaleQEA judges this with a model): {step.expected}"
                )
                lines.append("  // Exported as a manual check - assert it explicitly if you need it enforced here.")
            case StepAction.NOTE:
                lines.append(f"  // MANUAL STEP: {step.intent} → expected: {step.expected}")
            case _:
                lines.append(f"  // Unsupported in export: {step.action} ({step.intent})")
    lines.append("});")
    return "\n".join(line for line in lines if line is not None) + "\n"


def _playwright_py(case: TestCase, steps: list[TestStep], base_url: str) -> str:
    lines = [
        '"""Generated by GaleQEA - a standard pytest + Playwright test with no',
        "GaleQEA dependency.",
        "",
        f"Source test: {case.key} — {case.title}",
        f"Requirements: {', '.join(case.requirement_refs) or 'none recorded'}",
        '"""',
        "",
        "from playwright.sync_api import Page, expect",
        "",
        "",
        f"def test_{_slug(case.key)}(page: Page) -> None:",
    ]
    if not steps:
        lines.append("    pass")
    for step in steps:
        loc = _locator_ts(step).replace("page.getBy", "page.get_by").replace(
            "getByTestId", "get_by_test_id")
        loc = (loc.replace("get_byRole", "get_by_role").replace("get_byLabel", "get_by_label")
                  .replace("get_byPlaceholder", "get_by_placeholder")
                  .replace("get_byText", "get_by_text").replace("get_byAltText", "get_by_alt_text")
                  .replace("get_byTitle", "get_by_title"))
        loc = loc.replace("{ name: ", "name=").replace(" }", "").replace("{{", "").replace("}}", "")
        value = step.value or {}
        text = value.get("text", "")
        if step.intent:
            lines.append(f"    # {step.intent}")
        match step.action:
            case StepAction.GOTO:
                url = value.get("url", "/")
                full = url if url.startswith("http") else f"{base_url.rstrip('/')}{url}"
                lines.append(f"    page.goto({_q(full)})")
            case StepAction.CLICK:
                lines.append(f"    {loc}.click()")
            case StepAction.FILL:
                lines.append(f"    {loc}.fill({_q(text)})")
            case StepAction.EXPECT_VISIBLE:
                lines.append(f"    expect({loc}).to_be_visible()")
            case StepAction.EXPECT_TEXT:
                lines.append(f"    expect({loc}).to_contain_text({_q(text)})")
            case StepAction.EXPECT_URL:
                lines.append(f"    expect(page).to_have_url({_q(value.get('url', ''))})")
            case StepAction.NOTE:
                lines.append(f"    # MANUAL STEP: {step.intent} → expected: {step.expected}")
            case _:
                lines.append(f"    # Unsupported in export: {step.action}")
    return "\n".join(lines) + "\n"


def _robot(case: TestCase, steps: list[TestStep], base_url: str) -> str:
    lines = [
        "*** Settings ***",
        "Library    Browser",
        "",
        "*** Test Cases ***",
        f"{case.key} {case.title}",
        f"    [Documentation]    {case.rationale or case.title}",
        f"    [Tags]    {'    '.join(case.tags or ['galeqea'])}",
    ]
    for step in steps:
        target = (step.target or {}).get("accessible_name") or ""
        value = (step.value or {}).get("text", "")
        if step.action == StepAction.GOTO:
            lines.append(f"    New Page    {base_url}{(step.value or {}).get('url', '/')}")
        elif step.action == StepAction.CLICK:
            lines.append(f"    Click    text={target}")
        elif step.action == StepAction.FILL:
            lines.append(f"    Fill Text    text={target}    {value}")
        elif step.action == StepAction.EXPECT_TEXT:
            lines.append(f"    Get Text    text={target}    contains    {value}")
        else:
            lines.append(f"    Log    {step.action}: {step.intent}")
    return "\n".join(lines) + "\n"


def _cucumber(case: TestCase, steps: list[TestStep], base_url: str) -> str:
    lines = [
        f"# Generated by GaleQEA from {case.key}",
        f"@{' @'.join(case.tags or ['galeqea'])}",
        f"Feature: {case.title}",
        f"  {case.rationale}",
        "",
        f"  Scenario: {case.title}",
    ]
    for pre in case.preconditions or []:
        lines.append(f"    Given {pre}")
    keyword = "When"
    for step in steps:
        if step.action.startswith("expect"):
            lines.append(f"    Then {step.expected or step.intent}")
        else:
            lines.append(f"    {keyword} {step.intent}")
            keyword = "And"
    return "\n".join(lines) + "\n"


# --------------------------------------------------------------------------- #
def _q(value: str) -> str:
    escaped = str(value).replace("\\", "\\\\").replace("'", "\\'").replace("\n", "\\n")
    return f"'{escaped}'"


def _re(value: str) -> str:
    return str(value).replace("/", "\\/").replace(".", "\\.")


def _slug(value: str) -> str:
    return "".join(ch if ch.isalnum() else "_" for ch in value.lower()).strip("_")
