"""The root-cause analysis report: the latest RCA for one run, in two shapes.

A failed run is only actionable once someone knows *why*. This surfaces the most
recent confidence-scored, evidence-cited RCA for a run so a human or an agent can
read the leading hypothesis and its citations without re-deriving them. When no
analysis has been produced yet, it says so plainly rather than inventing one.
"""

from __future__ import annotations

from sqlalchemy import select

from ..models import RCAReport
from .common import cap_markdown, envelope, ui_href


def build_rca_report(db, project, run) -> dict:
    """The canonical JSON RCA report for a run. Deterministic; latest analysis."""
    rca = db.execute(
        select(RCAReport)
        .where(RCAReport.project_id == project.id, RCAReport.run_id == run.id)
        .order_by(RCAReport.created_at.desc(), RCAReport.id.desc())
    ).scalars().first()

    self_parts = ("runs", run.id, "rca", "report.json")

    if rca is None:
        return envelope(
            project.id, "rca", self_parts,
            {
                "available": False,
                "run_id": run.id,
                "ui_href": ui_href("runs", run.id),
                "note": "no root-cause analysis has been generated for this run yet",
            },
        )

    return envelope(
        project.id, "rca", self_parts,
        {
            "available": True,
            "id": rca.id,
            "run_id": run.id,
            "ui_href": ui_href("runs", run.id),
            "category": rca.category,
            "summary": rca.summary,
            "hypotheses": rca.hypotheses or [],
            "evidence": rca.evidence or [],
            "suspect_commits": rca.suspect_commits or [],
            "suggested_fix": rca.suggested_fix,
            "confidence": rca.confidence,
            "generated_by": rca.generated_by,
            "model": rca.model,
        },
    )


# --------------------------------------------------------------------------- #
# Markdown
# --------------------------------------------------------------------------- #
def rca_report_markdown(report: dict) -> str:
    lines = [f"# Root-cause analysis: run {report['run_id']}", ""]

    if not report.get("available"):
        lines.append(report.get("note", "No root-cause analysis is available for this run."))
        return cap_markdown("\n".join(lines) + "\n", report["href"])

    lines += [
        f"**{report['category']}** at {report['confidence']:.0%} confidence "
        f"(generated by {report['generated_by']}). {report['summary']}",
        "",
        "## Hypotheses",
        "",
    ]
    lines += _bullets(report["hypotheses"]) or ["_None._"]
    lines += ["", "## Evidence", ""]
    lines += _bullets(report["evidence"]) or ["_None._"]
    if report.get("suggested_fix"):
        lines += ["", "## Suggested fix", "", report["suggested_fix"]]

    return cap_markdown("\n".join(lines) + "\n", report["href"])


def _bullets(items: list) -> list[str]:
    """Render a list of hypotheses/evidence as bullets, whether the entries are
    plain strings or dicts carrying a statement/confidence."""
    out: list[str] = []
    for it in items:
        if isinstance(it, dict):
            text = it.get("statement") or it.get("summary") or it.get("detail") or str(it)
            conf = it.get("confidence")
            if isinstance(conf, (int, float)):
                out.append(f"- {text} ({conf:.0%})")
            else:
                out.append(f"- {text}")
        else:
            out.append(f"- {it}")
    return out
